import { expect, test } from '@playwright/test';
import type { ScanResponse } from '../src/types';

test('real API scan populates both views and exports the returned scene', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'API connected' })).toBeVisible();
  await expect(page.getByTestId('object-count')).toHaveText('—');
  await page.getByLabel('Scan name', { exact: true }).fill('Integration scan');
  const responsePromise = page.waitForResponse(r => r.url().endsWith('/api/scans') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Run demo scan' }).click();
  const response = await responsePromise;
  expect(response.status()).toBe(201);
  const scan = await response.json() as ScanResponse;
  expect(response.request().postDataJSON()).toEqual({ name: 'Integration scan', preset: 'office', source: 'demo' });
  await expect(page.getByTestId('object-count')).toHaveText(String(scan.stats.objects));
  await expect(page.getByTestId('scene-preview').locator('canvas')).toHaveAttribute('data-objects', String(scan.scene.objects.length));
  await expect(page.getByRole('status')).toContainText(scan.id.slice(0, 8));
  await page.screenshot({ path: 'test-results/dashboard.png', fullPage: true });
  await page.getByTestId('scene-preview').locator('canvas').click();
  await expect(page).toHaveURL(/#modeler$/);
  await expect(page.getByRole('heading', { name: scan.name })).toBeVisible();
  await expect(page.getByTestId('scene-modeler').locator('canvas')).toHaveAttribute('data-objects', String(scan.scene.objects.length));
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await page.getByRole('button', { name: 'Reset view' }).click();
  await page.screenshot({ path: 'test-results/modeler.png', fullPage: true });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export JSON' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe(`spatial-scan-${scan.id}.json`);
  const stream = await download.createReadStream();
  const chunks: Buffer[] = [];
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk));
  expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual(scan);
  await page.getByRole('button', { name: 'Return to dashboard' }).click();
  await page.getByLabel('Sample capture').selectOption('corridor');
  await page.getByRole('button', { name: 'Run demo scan' }).click();
  await expect(page.getByTestId('object-count')).toHaveText('4');
  expect(errors).toEqual([]);
});

test('loading, failed request, retry, and previous successful scene', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Run demo scan' }).click();
  await expect(page.getByTestId('object-count')).toHaveText('6');
  let release!: () => void;
  const gate = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/api/scans', async route => { await gate; await route.abort('failed'); });
  await page.getByRole('button', { name: 'Run demo scan' }).click();
  await expect(page.getByRole('button', { name: 'Processing scan' })).toBeDisabled();
  await expect(page.getByRole('status')).toContainText('Waiting for the reconstruction response');
  release();
  await expect(page.getByRole('alert')).toContainText('Cannot reach the API');
  await expect(page.getByRole('alert')).toContainText('previous successful scan');
  await expect(page.getByTestId('object-count')).toHaveText('6');
  await page.unroute('**/api/scans');
  await page.getByLabel('Sample capture').selectOption('corridor');
  await page.getByRole('button', { name: 'Retry demo scan' }).click();
  await expect(page.getByTestId('object-count')).toHaveText('4');
  await expect(page.getByRole('alert')).toHaveCount(0);
});

test('mobile layout and modeler deep link work before scanning', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#modeler');
  await expect(page.getByRole('button', { name: 'Export JSON' })).toBeDisabled();
  await expect(page.getByText('Your space, reconstructed').last()).toBeVisible();
  await page.getByRole('button', { name: 'Return to dashboard' }).click();
  await page.getByRole('button', { name: 'Run demo scan' }).click();
  await expect(page.getByTestId('object-count')).toHaveText('6');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Open the full 3D modeling environment' }).click();
  await expect(page.getByRole('button', { name: 'Return to dashboard' })).toBeInViewport();
  await expect(page.getByTestId('scene-modeler').locator('canvas')).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollHeight <= innerHeight + 1)).toBe(true);
  await expect(page.getByRole('region', { name: '3D modeling environment', exact: true })).toHaveCSS('opacity', '1');
  await page.screenshot({ path: 'test-results/mobile-modeler.png', fullPage: true });
});
